# What is numpy array?
A numpy array is a powerful n-dimensional array object which is in the form of rows and columns. It is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. In NumPy, dimensions are called axes. The number of axes is referred to as the rank.

In [55]:
import numpy as np

# 1D array

In [56]:
a = np.arange(6)
print(a)
np.shape(a)

[0 1 2 3 4 5]


(6,)

# 2D array

In [57]:
a1 = a[np.newaxis, : ]
print(a1)
np.shape(a1)

[[0 1 2 3 4 5]]


(1, 6)

# 3D array

In [58]:
a2 = a1[np.newaxis, :]
print(a2)
np.shape(a2)

[[[0 1 2 3 4 5]]]


(1, 1, 6)

# Creating Nunpy array

In [59]:
a = np.array([1,2,3,4,4,5,6,8,])
a.shape
print(a)

[1 2 3 4 4 5 6 8]


In [60]:
b = np.array([[1,2,3,4,5], [6,7,8,9,0]])
b.shape
print(b)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [61]:
b.dtype # Data type of array

dtype('int64')

In [62]:
type(b) # type of array

numpy.ndarray

In [63]:
# initialize array 
zeros = np.zeros((4,4))
print(zeros)
zeros.shape

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


(4, 4)

In [64]:
once = np.ones((4,4))
print(once)
once.shape

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


(4, 4)

In [65]:
full = np.full((3,3), 7)   
print(full)
full.shape

[[7 7 7]
 [7 7 7]
 [7 7 7]]


(3, 3)

In [66]:
identity = np.eye(3,4) # creating an identity matrix
identity.shape
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


# Array attribute

In [67]:
a.shape

(8,)

In [68]:
len(a)

8

In [69]:
a.ndim # Show diminsion

1

In [70]:
a.size

8

# **Basic operation**