# **NumPy (Part 2)**

In [2]:
import numpy as np

In [ ]:
# Empty array
empty = np.empty((3,2))
empty
print(empty[2])

[6.87298650e-038 4.17201348e-309]


In [ ]:
# array of even number using arange function starting to 2 and ending on 20 step is 2
even = np.arange(2, 21, 2)
print(even)

[ 2  4  6  8 10 12 14 16 18 20]


In [18]:
# array of add number using arange function starting to 1 and ending on 22 step is 2
odd = np.arange(1,23, 2)
print(odd)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [22]:
# starting point and ending point and num=10 how to many number do you want
lin = np.linspace(1, 10, num=10) 
lin

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
# how to give dtype to array
a = np.arange(1,10, 1, dtype=np.float64)
print(a)
a.dtype

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float64')

In [31]:
# how to sort array 
arr = np.array([1,4,6,9,4,2,7,0,7,5,997,3,223,53,64])
arr = np.sort(arr)
print(arr)

[  0   1   2   3   4   4   5   6   7   7   9  53  64 223 997]


In [39]:
# concatenate array
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c = np.concatenate((a,b), axis=0)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]
