# **NumPy (Part 2)**

In [2]:
import numpy as np

In [3]:
# Empty array
empty = np.empty((3,2))
empty
print(empty[2])

[0. 0.]


In [4]:
# array of even number using arange function starting to 2 and ending on 20 step is 2
even = np.arange(2, 21, 2)
print(even)

[ 2  4  6  8 10 12 14 16 18 20]


In [5]:
# array of add number using arange function starting to 1 and ending on 22 step is 2
odd = np.arange(1,23, 2)
print(odd)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [6]:
# starting point and ending point and num=10 how to many number do you want
lin = np.linspace(1, 10, num=10) 
lin

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
# how to give dtype to array
a = np.arange(1,10, 1, dtype=np.float64)
print(a)
a.dtype

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float64')

In [8]:
# how to sort array 
arr = np.array([1,4,6,9,4,2,7,0,7,5,997,3,223,53,64])
arr = np.sort(arr)
print(arr)

[  0   1   2   3   4   4   5   6   7   7   9  53  64 223 997]


In [9]:
# concatenate array
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c = np.concatenate((a,b), axis=0)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
# create 3D array
array = np.array([[[1,2,3],
                   [4,5,6]],
                  [[7,8,9],
                   [10,11,12]]])
array.shape
array.ndim
array.reshape(3, 4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
# convert 1D into 2D array
a = np.array([1,2,3,4,5])
print(a.shape)
a2 = a[np.newaxis, : ]
print(a2.shape)

(5,)
(1, 5)


# **Indexing and Slicing**

In [12]:
array = np.array([1,2,3,4,5,6,7,8,9])
array[0:8]
array[3:6]
array[1:4]

array([2, 3, 4])

In [13]:
# Create a 3D array
array = np.array([[[1,2,3],
                   [4,5,6]],
                   
                  [[7,8,9],
                   [10,11,12]]])
array.shape
array.ndim
array.reshape(4, 3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
print(array[0,1, :])

[4 5 6]


In [15]:
print(array[1,0, :])

[7 8 9]


In [16]:
array[array < 3]

array([1, 2])

# Making an array from another array


In [17]:
array = np.arange(1,50 ,2)
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [18]:
New_array = array[4:12]
New_array

array([ 9, 11, 13, 15, 17, 19, 21, 23])

In [19]:
# Hstake
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.hstack((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
#Vstake
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
# Create a matrix
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Creating big matrix
array = np.arange(1,100, 2).reshape(5, 10)
array

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [29]:
# Slicing a matrix
array[2 , 2:3]

array([45])

In [30]:
# lets access just '91'
array[-1, 5:6]

array([91])

In [31]:
# lets find max value in array
array.max()

np.int64(99)

In [36]:
# lets find min value in array / min in row
array.min(axis=1)

array([ 1, 21, 41, 61, 81])

In [ ]:
# lets check sum of all columns or rows
array.sum(axis=1)

array([100, 300, 500, 700, 900])